spring:
  application:
    name: modulith-example
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    partition-count: 1
    replication-factor: 1
    max-request-size: 20971520
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true